#!/bin/bash
if [ ! "$FM_ROOT" ]; then
	echo "FM_ROOT must be defined" 1>&2
	exit 1
fi
PATH=/bin:/usr/bin:$HOME/bin:$FM_ROOT
export FM_ROOT

case $1 in
	update|u|up)
		shift 
		source fm-update.sh $*
	;;
	search)
		shift 
		source fm-search.sh $*
	;;
	toc)
		shift 
		source fm-toc.sh $*
	;;
	init)
		shift 
		source fm-init.sh $*
	;;
	*)
		source fm-bin.sh $*
esac
